services:
  app:
    ports:
      - "8080:8080"
    build: ./app
    networks:
      - secbox

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - secbox

  mongo:
    image: mongo
    restart: always
    # environment:
    ports:
      - "27017:27017"
    networks:
      - secbox

  # host:
  #   build: ./host

networks:
  secbox:
    driver: bridge
